// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cyxufdzkpouwypgxibxo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImN5eHVmZHprcG91d3lwZ3hpYnhvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk5MTA5OTgsImV4cCI6MjA2NTQ4Njk5OH0.HNUTvJvTdWTwTgcLxNdhW-_x47GJP_P-BnGCi5Adx4k";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);